CREATE DATABASE FACEDETECT;

CREATE TABLE users(
   id SERIAL PRIMARY KEY,
   username VARCHAR (100),
   email text UNIQUE NOT NULL,
   entries BIGINT DEFAULT 0,
   joined TIMESTAMP NOT NULL
);

SELECT * FROM users;

CREATE TABLE login (
   id SERIAL PRIMARY KEY,
   hash VARCHAR(100) NOT NULL,  
   email text UNIQUE NOT NULL
);
